### ISSUE TITLE
Merge all docs

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.store#19]
- [ ] merge doc/store into README

- [ ] merge doc/build into README

- [x] replace https://wiki.eclipse.org/Lyo/Store with a stub pointing to the README

cc @jadelkhoury @jamsden

**Comment by berezovskyi** [comment]
@kartben I think you have done it some time ago? Please reopen if not.

**Comment by jadelkhoury** [comment]
Yes, the wiki page on eclipse points here. 
You know best what is under the docs folder, but it does look empty too.
