### ISSUE TITLE
Review ConsumerStore from lyo.server

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.store#2]
See org.eclipse.lyo.server.oauth.core

Focus on the concurrency handling!

**Comment by berezovskyi** [comment]
@jadelkhoury exactly what you looked at as well!

**Comment by berezovskyi** [comment]
can't recall what was that about; wontfix

**Comment by jadelkhoury** [comment]
No idea. very little information is provided, so happy to close.
