### ISSUE TITLE
Revert Jena Libs Dependency Change in Pom

### ISSUE THREAD

**Issue by yashkhatri** [eclipse/lyo.store#34]
The Jena-libs dependency type is set to POM. This is preventing build in oslc4j-bundle in lyo core. Replace this with the dependencies with in this POM file instead.

**Comment by berezovskyi** [comment]
What's the status on this one?

**Comment by yashkhatri** [comment]
The commits are merged in master. Seems like we can close the issue.

**Comment by jadelkhoury** [comment]
@yashkhatri But I see "<artifactId>apache-jena-libs</artifactId>" in the pom file still. Are you sure this is cllosed?

**Comment by yashkhatri** [comment]
@jadelkhoury Yes. Firstly, we removed apache-jena-libs from the pom file and added the individual Jena Libraries. This was done to enable bundling of Jena-Core. Then, we found a solution to exclude apache-jena-libs when bundling and include independent libraries as dependency in the bundle's pom file it-self and it worked. So we don't need this change anymore.

**Comment by jadelkhoury** [comment]
ok then.
